run:
  timeout: 5m

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  govet:
    check-shadowing: true
  gocyclo:
    min-complexity: 10
  staticcheck:
    checks: ["all"]

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - gocyclo
    - gofmt
    - goimports
    - unused
    - deadcode

issues:
  exclude-rules:
    - linters:
        - errcheck
      text: "ignored return value"
    - linters:
        - staticcheck
      text: "SA4006"

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
